prometheus:
  prometheusSpec:
    secrets:
    - etcd-client

kubeEtcd:
  endpoints: ((endpoints))
  service:
    port: 2379
    targetPort: 2379
  serviceMonitor:
    scheme: https
    insecureSkipVerify: true
    caFile: /etc/prometheus/secrets/etcd-client/etcd-client-ca.crt
    certFile: /etc/prometheus/secrets/etcd-client/etcd-client.crt
    keyFile: /etc/prometheus/secrets/etcd-client/etcd-client.key

kubeScheduler:
  endpoints: ((endpoints))
  serviceMonitor:
    interval: 30s
    insecureSkipVerify: true
