prometheus:
  prometheusSpec:
    secrets:
      - etcd-client

additionalScrapeConfigs:
- job_name: "kubeEtcd-((cluster_name))"
  file_sd_configs:
  - files:
    - '/etc/prometheus/configmaps/bosh-target-groups/bosh_target_groups.json'
  scheme: https
  tls_config:
    ca_file: "/etc/prometheus/secrets/etcd-client/etcd-client-ca.crt"
    cert_file: "/etc/prometheus/secrets/etcd-client/etcd-client.crt"
    key_file:  "/etc/prometheus/secrets/etcd-client/etcd-client.key"
    server_name: "*.etcd.cfcr.internal"
  relabel_configs:
  - source_labels: [__meta_bosh_job_process_name]
    regex: etcd
    action: keep
  - source_labels: [__meta_bosh_deployment]
    regex: ((service_instance_id))
    action: keep
  - source_labels: [__address__]
    regex:  '(.*)'
    target_label: __address__
    replacement: '${1}:2379'

kubeEtcd:
  endpoints: ((endpoints))
  service:
    port: 4001
    targetPort: 4001
    selector:
     "k8s-app": "etcd-manager-main"
  serviceMonitor:
    scheme: https
    insecureSkipVerify: true
    caFile:   /etc/prometheus/secrets/etcd-certs/ca.crt
    certFile: /etc/prometheus/secrets/etcd-certs/client.crt
    keyFile:  /etc/prometheus/secrets/etcd-certs/client.key
